<?php

declare(strict_types=1);

namespace EduCRM\Services;

/**
 * Appointment Service
 * Handles appointment scheduling and management
 */

class AppointmentService
{
    private \PDO $pdo;

    public function __construct(\PDO $pdo)
    {
        $this->pdo = $pdo;
    }

    /**
     * Create a new appointment
     */
    public function createAppointment($data)
    {
        $stmt = $this->pdo->prepare("
            INSERT INTO appointments (
                student_id, inquiry_id, counselor_id,
                title, description, appointment_date,
                duration_minutes, location, meeting_link, status
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ");

        $result = $stmt->execute([
            $data['student_id'] ?? null,
            $data['inquiry_id'] ?? null,
            $data['counselor_id'],
            $data['title'],
            $data['description'] ?? null,
            $data['appointment_date'],
            $data['duration_minutes'] ?? 30,
            $data['location'] ?? null,
            $data['meeting_link'] ?? null,
            'scheduled'
        ]);

        // Phase 2B & 3B: Queue reminder email and SMS for 24 hours before appointment
        if ($result) {
            $appointmentId = $this->pdo->lastInsertId();
            $appointmentDateTime = strtotime($data['appointment_date']);
            $reminderTime = date('Y-m-d H:i:s', $appointmentDateTime - (24 * 3600)); // 24 hours before

            // Only schedule reminder if appointment is more than 24 hours away
            if ($appointmentDateTime > (time() + (24 * 3600))) {
                try {
                    // Send SMS reminder (Phase 3B)
                    $this->sendAppointmentSMS($appointmentId, 'reminder');

                    require_once dirname(__DIR__) . '/services/EmailNotificationService.php';
                    $emailService = new \EduCRM\Services\EmailNotificationService($this->pdo);

                    // Queue the reminder to be sent 24 hours before
                    $this->pdo->prepare("
                        INSERT INTO email_queue (recipient_email, recipient_name, subject, body, template, scheduled_at)
                        SELECT 
                            u.email,
                            u.name,
                            CONCAT('Appointment Reminder: ', ?),
                            'Reminder email will be generated by cron job',
                            'appointment_reminder',
                            ?
                        FROM users u
                        WHERE u.id = ?
                    ")->execute([$data['title'], $reminderTime, $data['counselor_id']]);

                } catch (\Exception $e) {
                    // Log error but don't fail appointment creation
                    error_log("Failed to queue appointment reminder: " . $e->getMessage());
                }
            }
        }

        return $result;
    }

    /**
     * Get appointment by ID
     */
    public function getAppointment($appointmentId)
    {
        $stmt = $this->pdo->prepare("
            SELECT 
                a.*,
                u1.name as student_name,
                u1.email as student_email,
                u2.name as counselor_name,
                i.name as inquiry_name,
                i.email as inquiry_email
            FROM appointments a
            LEFT JOIN users u1 ON a.student_id = u1.id
            LEFT JOIN users u2 ON a.counselor_id = u2.id
            LEFT JOIN inquiries i ON a.inquiry_id = i.id
            WHERE a.id = ?
        ");
        $stmt->execute([$appointmentId]);
        return $stmt->fetch(\PDO::FETCH_ASSOC);
    }

    /**
     * Get appointments for a counselor
     */
    public function getCounselorAppointments($counselorId, $filters = [])
    {
        $sql = "
            SELECT 
                a.*,
                u1.name as student_name,
                u2.name as counselor_name,
                i.name as inquiry_name
            FROM appointments a
            LEFT JOIN users u1 ON a.student_id = u1.id
            LEFT JOIN users u2 ON a.counselor_id = u2.id
            LEFT JOIN inquiries i ON a.inquiry_id = i.id
            WHERE a.counselor_id = ?
        ";

        $params = [$counselorId];

        // Apply filters
        if (isset($filters['status'])) {
            $sql .= " AND a.status = ?";
            $params[] = $filters['status'];
        }

        if (isset($filters['date_from'])) {
            $sql .= " AND a.appointment_date >= ?";
            $params[] = $filters['date_from'];
        }

        if (isset($filters['date_to'])) {
            $sql .= " AND a.appointment_date <= ?";
            $params[] = $filters['date_to'];
        }

        $sql .= " ORDER BY a.appointment_date ASC";

        $stmt = $this->pdo->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll(\PDO::FETCH_ASSOC);
    }

    /**
     * Get all appointments (for admin)
     */
    public function getAllAppointments($filters = [])
    {
        $sql = "
            SELECT 
                a.*,
                u1.name as student_name,
                u2.name as counselor_name,
                i.name as inquiry_name
            FROM appointments a
            LEFT JOIN users u1 ON a.student_id = u1.id
            LEFT JOIN users u2 ON a.counselor_id = u2.id
            LEFT JOIN inquiries i ON a.inquiry_id = i.id
            WHERE 1=1
        ";

        $params = [];

        // Apply filters
        if (isset($filters['status'])) {
            $sql .= " AND a.status = ?";
            $params[] = $filters['status'];
        }

        if (isset($filters['counselor_id'])) {
            $sql .= " AND a.counselor_id = ?";
            $params[] = $filters['counselor_id'];
        }

        if (isset($filters['date_from'])) {
            $sql .= " AND a.appointment_date >= ?";
            $params[] = $filters['date_from'];
        }

        if (isset($filters['date_to'])) {
            $sql .= " AND a.appointment_date <= ?";
            $params[] = $filters['date_to'];
        }

        $sql .= " ORDER BY a.appointment_date ASC";

        $stmt = $this->pdo->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll(\PDO::FETCH_ASSOC);
    }

    /**
     * Update appointment
     */
    public function updateAppointment($appointmentId, $data)
    {
        $fields = [];
        $params = [];

        if (isset($data['title'])) {
            $fields[] = "title = ?";
            $params[] = $data['title'];
        }

        if (isset($data['description'])) {
            $fields[] = "description = ?";
            $params[] = $data['description'];
        }

        if (isset($data['appointment_date'])) {
            $fields[] = "appointment_date = ?";
            $params[] = $data['appointment_date'];
        }

        if (isset($data['duration_minutes'])) {
            $fields[] = "duration_minutes = ?";
            $params[] = $data['duration_minutes'];
        }

        if (isset($data['location'])) {
            $fields[] = "location = ?";
            $params[] = $data['location'];
        }

        if (isset($data['meeting_link'])) {
            $fields[] = "meeting_link = ?";
            $params[] = $data['meeting_link'];
        }

        if (isset($data['status'])) {
            $fields[] = "status = ?";
            $params[] = $data['status'];
        }

        if (isset($data['notes'])) {
            $fields[] = "notes = ?";
            $params[] = $data['notes'];
        }

        if (empty($fields))
            return false;

        $params[] = $appointmentId;

        $sql = "UPDATE appointments SET " . implode(', ', $fields) . " WHERE id = ?";
        $stmt = $this->pdo->prepare($sql);

        return $stmt->execute($params);
    }

    /**
     * Delete an appointment
     */
    public function deleteAppointment($id)
    {
        $stmt = $this->pdo->prepare("DELETE FROM appointments WHERE id = ?");
        return $stmt->execute([$id]);
    }

    /**
     * Phase 2: Get appointments by date range for calendar view
     */
    public function getAppointmentsByDateRange($startDate, $endDate, $counselorId = null)
    {
        $sql = "SELECT a.*, 
                u1.name as student_name,
                i.name as inquiry_name,
                u2.name as counselor_name
            FROM appointments a
            LEFT JOIN users u1 ON a.student_id = u1.id
            LEFT JOIN inquiries i ON a.inquiry_id = i.id
            LEFT JOIN users u2 ON a.counselor_id = u2.id
            WHERE a.appointment_date BETWEEN ? AND ?";

        $params = [$startDate, $endDate];

        if ($counselorId) {
            $sql .= " AND a.counselor_id = ?";
            $params[] = $counselorId;
        }

        $sql .= " ORDER BY a.appointment_date ASC";

        $stmt = $this->pdo->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll(\PDO::FETCH_ASSOC);
    }

    /**
     * Phase 2: Reschedule an appointment with conflict detection
     */
    public function rescheduleAppointment($id, $newDate, $duration = null)
    {
        // Get current appointment
        $appointment = $this->getAppointment($id);
        if (!$appointment) {
            return false;
        }

        $durationToUse = $duration ?? $appointment['duration_minutes'];

        // Check for conflicts at new time (excluding this appointment)
        $sql = "SELECT COUNT(*) FROM appointments 
                WHERE counselor_id = ? 
                AND id != ?
                AND status = 'scheduled'
                AND (
                    (appointment_date <= ? AND DATE_ADD(appointment_date, INTERVAL duration_minutes MINUTE) > ?) OR
                    (appointment_date < DATE_ADD(?, INTERVAL ? MINUTE) AND appointment_date >= ?)
                )";

        $stmt = $this->pdo->prepare($sql);
        $stmt->execute([
            $appointment['counselor_id'],
            $id,
            $newDate,
            $newDate,
            $newDate,
            $durationToUse,
            $newDate
        ]);

        if ($stmt->fetchColumn() > 0) {
            return false; // Conflict exists
        }

        // Update appointment
        $updateSql = "UPDATE appointments SET appointment_date = ?";
        $params = [$newDate];

        if ($duration) {
            $updateSql .= ", duration_minutes = ?";
            $params[] = $duration;
        }

        $updateSql .= " WHERE id = ?";
        $params[] = $id;

        $stmt = $this->pdo->prepare($updateSql);
        return $stmt->execute($params);
    }

    /**
     * Phase 2: Get calendar events in FullCalendar format
     */
    public function getCalendarEvents($startDate, $endDate, $counselorId = null)
    {
        $appointments = $this->getAppointmentsByDateRange($startDate, $endDate, $counselorId);
        $events = [];

        foreach ($appointments as $apt) {
            $clientName = $apt['student_name'] ?? $apt['inquiry_name'] ?? 'No Client';

            // Color coding by status
            $colors = [
                'scheduled' => '#3b82f6', // blue
                'completed' => '#10b981', // green
                'cancelled' => '#ef4444', // red
                'no_show' => '#f59e0b'    // orange
            ];

            $events[] = [
                'id' => $apt['id'],
                'title' => $apt['title'],
                'start' => $apt['appointment_date'],
                'end' => date('Y-m-d H:i:s', strtotime($apt['appointment_date'] . ' +' . $apt['duration_minutes'] . ' minutes')),
                'backgroundColor' => $colors[$apt['status']] ?? '#6b7280',
                'borderColor' => $colors[$apt['status']] ?? '#6b7280',
                'extendedProps' => [
                    'client' => $clientName,
                    'counselor' => $apt['counselor_name'],
                    'location' => $apt['location'],
                    'meeting_link' => $apt['meeting_link'],
                    'status' => $apt['status'],
                    'description' => $apt['description']
                ]
            ];
        }

        return $events;
    }

    /**
     * Get upcoming appointments count
     */
    public function getUpcomingAppointmentsCount($counselorId, $days = 7)
    {
        $stmt = $this->pdo->prepare("
            SELECT COUNT(*) as count
            FROM appointments
            WHERE counselor_id = ?
            AND status = 'scheduled'
            AND appointment_date BETWEEN NOW() AND DATE_ADD(NOW(), INTERVAL ? DAY)
        ");
        $stmt->execute([$counselorId, $days]);
        $result = $stmt->fetch(\PDO::FETCH_ASSOC);
        return (int) $result['count'];
    }

    /**
     * Get upcoming appointments
     */
    public function getUpcomingAppointments($counselorId, $days = 7)
    {
        $stmt = $this->pdo->prepare("
            SELECT 
                a.*,
                u1.name as student_name,
                u2.name as counselor_name,
                i.name as inquiry_name
            FROM appointments a
            LEFT JOIN users u1 ON a.student_id = u1.id
            LEFT JOIN users u2 ON a.counselor_id = u2.id
            LEFT JOIN inquiries i ON a.inquiry_id = i.id
            WHERE a.counselor_id = ?
            AND a.status = 'scheduled'
            AND a.appointment_date BETWEEN NOW() AND DATE_ADD(NOW(), INTERVAL ? DAY)
            ORDER BY a.appointment_date ASC
        ");
        $stmt->execute([$counselorId, $days]);
        return $stmt->fetchAll(\PDO::FETCH_ASSOC);
    }

    /**
     * Get appointments for calendar view
     */
    public function getCalendarAppointments($counselorId, $startDate, $endDate)
    {
        $stmt = $this->pdo->prepare("
            SELECT 
                a.id,
                a.title,
                a.appointment_date as start,
                DATE_ADD(a.appointment_date, INTERVAL a.duration_minutes MINUTE) as end,
                a.status,
                a.location,
                COALESCE(u1.name, i.name) as client_name
            FROM appointments a
            LEFT JOIN users u1 ON a.student_id = u1.id
            LEFT JOIN inquiries i ON a.inquiry_id = i.id
            WHERE a.counselor_id = ?
            AND a.appointment_date BETWEEN ? AND ?
            ORDER BY a.appointment_date ASC
        ");
        $stmt->execute([$counselorId, $startDate, $endDate]);
        return $stmt->fetchAll(\PDO::FETCH_ASSOC);
    }

    /**
     * Check for appointment conflicts
     */
    public function checkConflict($counselorId, $appointmentDate, $durationMinutes, $excludeId = null)
    {
        $endTime = date('Y-m-d H:i:s', strtotime($appointmentDate) + ($durationMinutes * 60));

        $sql = "
            SELECT COUNT(*) as count
            FROM appointments
            WHERE counselor_id = ?
            AND status = 'scheduled'
            AND (
                (appointment_date <= ? AND DATE_ADD(appointment_date, INTERVAL duration_minutes MINUTE) > ?)
                OR
                (appointment_date < ? AND DATE_ADD(appointment_date, INTERVAL duration_minutes MINUTE) >= ?)
            )
        ";

        $params = [$counselorId, $appointmentDate, $appointmentDate, $endTime, $endTime];

        if ($excludeId) {
            $sql .= " AND id != ?";
            $params[] = $excludeId;
        }

        $stmt = $this->pdo->prepare($sql);
        $stmt->execute($params);
        $result = $stmt->fetch(\PDO::FETCH_ASSOC);

        return (int) $result['count'] > 0;
    }

    /**
     * Get appointments for a student/inquiry
     */
    public function getEntityAppointments($entityType, $entityId)
    {
        $field = $entityType === 'student' ? 'student_id' : 'inquiry_id';

        $stmt = $this->pdo->prepare("
            SELECT 
                a.*,
                u.name as counselor_name
            FROM appointments a
            LEFT JOIN users u ON a.counselor_id = u.id
            WHERE a.$field = ?
            ORDER BY a.appointment_date DESC
        ");
        $stmt->execute([$entityId]);
        return $stmt->fetchAll(\PDO::FETCH_ASSOC);
    }

    /**
     * Send appointment SMS notification
     * 
     * @param int $appointmentId Appointment ID
     * @param string $type Message type: 'reminder', 'confirmation', 'cancellation'
     * @return bool Success status
     */
    private function sendAppointmentSMS($appointmentId, $type = 'reminder')
    {
        try {
            // Get appointment details with contact info
            $appointment = $this->getAppointment($appointmentId);
            if (!$appointment) {
                return false;
            }

            // Determine recipient phone number (student or inquiry)
            $recipientPhone = null;
            $recipientName = null;

            if ($appointment['student_id']) {
                $stmt = $this->pdo->prepare("SELECT phone, name FROM users WHERE id = ?");
                $stmt->execute([$appointment['student_id']]);
                $student = $stmt->fetch(\PDO::FETCH_ASSOC);
                $recipientPhone = $student['phone'] ?? null;
                $recipientName = $student['name'] ?? 'Student';
            } elseif ($appointment['inquiry_id']) {
                $stmt = $this->pdo->prepare("SELECT phone, name FROM inquiries WHERE id = ?");
                $stmt->execute([$appointment['inquiry_id']]);
                $inquiry = $stmt->fetch(\PDO::FETCH_ASSOC);
                $recipientPhone = $inquiry['phone'] ?? null;
                $recipientName = $inquiry['name'] ?? 'Client';
            }

            // No phone number available
            if (empty($recipientPhone)) {
                error_log("Appointment SMS: No phone number for appointment #$appointmentId");
                return false;
            }

            // Build message based on type
            $appointmentDate = date('l, F j, Y \a\t g:i A', strtotime($appointment['appointment_date']));
            $messages = [
                'reminder' => "Hi $recipientName, this is a reminder for your appointment \"{$appointment['title']}\" on $appointmentDate. Location: " . ($appointment['location'] ?? 'TBD'),
                'confirmation' => "Hi $recipientName, your appointment \"{$appointment['title']}\" has been confirmed for $appointmentDate.",
                'cancellation' => "Hi $recipientName, your appointment \"{$appointment['title']}\" scheduled for $appointmentDate has been cancelled."
            ];

            $message = $messages[$type] ?? $messages['reminder'];

            // Try to send via MessagingFactory
            require_once dirname(__FILE__) . '/MessagingFactory.php';
            \EduCRM\Services\MessagingFactory::init($this->pdo);

            $gateway = \EduCRM\Services\MessagingFactory::create(null, 'sms');
            $result = $gateway->send($recipientPhone, $message);

            return $result['success'] ?? false;

        } catch (\Exception $e) {
            // Log but don't fail - SMS is optional
            error_log("Appointment SMS failed: " . $e->getMessage());
            return false;
        }
    }
}
